// object type
// generated by http://json2ts.com/

export interface ObjectItem {
  uuid: string;
  file: string;
  preview: string;
  name: string;
  link: string;
  image: string;
  states: string[];
  slots: string[];
  attachable: string[];
  specs: Map<string, string>;
}

// user saved object date
export interface SavedObjectItem {
  id: string;
  parentId: string;
  color: string;
  material: string;
  state: string;
  position: string;
  rotation: string;
  scale: string;
}